Core/FileHandler:
  ignorePaths: ["**/otp-base/**"]

File/PageHandler:
  defaultMetaInfo:
    blocks: [[content, markdown]]

File/CopyHandler:
    paths: ["**/*.css", "**/*.jpg", "**/*.tar.gz", "**/*.gif", "**/*.xml"]

MenuStyle/Vertical:
  maxLevels: 4